# tical-code -- AI Agent Platform
# Copyright (C) 2026 zizetu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Original repository: https://github.com/zizetu/eite-agent
#

"""
Tool Call Parser - Extract Tool Calls from EITE Evaluation Responses
=====================================================================

Parses AI model responses to extract tool call instructions in JSON format.
Used by the EITE evaluation framework to extract and validate tool calls
generated by evaluated agents during benchmark runs.

Supports multiple formats including pure JSON, JSON in code blocks,
and JSON embedded in explanatory text.

EITE Version: 1.0.0
"""

import json
import re
import logging
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class ToolCallParseError(Exception):
    """Raised when tool call parsing fails during evaluation."""
    pass


def parse_tool_calls(text: str) -> List[Dict[str, Any]]:
    """
    Parse tool calls from AI model response text.

    Supports multiple formats:
    1. Pure JSON: {"tool": "name", "params": {...}}
    2. JSON in code block: ```json\n{"tool": "name", ...}\n```
    3. JSON with explanation: Some text {"tool": "name", ...} more text
    4. Nested params: {"tool": "x", "params": {"nested": {"a": 1}}}

    Uses json.loads() layer-by-layer scan, not complex regex that
    excludes nested structures.

    Args:
        text: AI model response text

    Returns:
        List of parsed tool call dicts
    """
    if not text:
        return []

    tool_calls = []
    text = text.strip()

    # Strategy 1: use JSON parser to scan, not regex that excludes nested structures
    tool_calls.extend(_parse_json_candidates(text))

    # Strategy 2: Look for code blocks with JSON
    code_block_pattern = r'```(?:json)?\s*\n?(.*?)\n?\s*```'
    for match in re.finditer(code_block_pattern, text, re.DOTALL):
        block_content = match.group(1).strip()
        if '{"tool"' in block_content or '"tool":' in block_content:
            try:
                parsed = json.loads(block_content)
                if isinstance(parsed, dict) and 'tool' in parsed:
                    tool_calls.append(parsed)
                elif isinstance(parsed, list):
                    for item in parsed:
                        if isinstance(item, dict) and 'tool' in item:
                            tool_calls.append(item)
            except json.JSONDecodeError:
                # try to fix common JSON problems
                fixed = _fix_json(block_content)
                if fixed:
                    try:
                        parsed = json.loads(fixed)
                        if isinstance(parsed, dict) and 'tool' in parsed:
                            tool_calls.append(parsed)
                        elif isinstance(parsed, list):
                            for item in parsed:
                                if isinstance(item, dict) and 'tool' in item:
                                    tool_calls.append(item)
                    except json.JSONDecodeError:
                        logger.debug("tool_call_parser: code block JSON parse failed")

    # Strategy 3: Try direct JSON parse if text is pure JSON
    if text.startswith('{') and text.endswith('}'):
        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict) and 'tool' in parsed:
                tool_calls.append(parsed)
        except json.JSONDecodeError:
            logger.debug("tool_call_parser: direct JSON parse failed")

    # Deduplicate by tool name and params hash
    seen = set()
    unique_calls = []
    for call in tool_calls:
        key = (call.get('tool'), json.dumps(call.get('params', {}), sort_keys=True))
        if key not in seen:
            seen.add(key)
            unique_calls.append(call)

    return unique_calls


def _parse_json_candidates(text: str) -> List[Dict[str, Any]]:
    """
    Scan text to find all possible JSON objects, attempt to parse as tool calls.

    Uses json.loads() rather than complex regex, supporting nested structures.

    Algorithm:
    1. Find all '{' positions as candidate starting points
    2. From each starting point, attempt to find a complete (balanced) JSON object
    3. Use json.loads() to verify; if valid and contains 'tool' key, include it
    """
    tool_calls = []

    # Find all '{' positions
    brace_positions = [i for i, c in enumerate(text) if c == '{']

    for start_pos in brace_positions:
        # Skip already processed positions (avoid duplicates)
        if start_pos > 0 and text[start_pos - 1] == '"':
            continue

        # Attempt to find a complete JSON object
        json_candidate = _extract_json_object(text, start_pos)
        if not json_candidate:
            continue

        # Attempt to parse
        try:
            parsed = json.loads(json_candidate)
            # Verify it is a valid tool call
            if isinstance(parsed, dict) and 'tool' in parsed and isinstance(parsed['tool'], str):
                tool_calls.append(parsed)
        except json.JSONDecodeError:
            # Try to fix common JSON problems
            fixed = _fix_json(json_candidate)
            if fixed:
                try:
                    parsed = json.loads(fixed)
                    if isinstance(parsed, dict) and 'tool' in parsed and isinstance(parsed['tool'], str):
                        tool_calls.append(parsed)
                except json.JSONDecodeError:
                    logger.debug("tool_call_parser: JSON still failed after fix")

    return tool_calls


def _extract_json_object(text: str, start_pos: int) -> Optional[str]:
    """
    Extract a complete (balanced) JSON object from a given position.

    Args:
        text: complete text
        start_pos: position of the '{'

    Returns:
        Complete JSON string, or None if extraction is not possible
    """
    if start_pos >= len(text) or text[start_pos] != '{':
        return None

    # Compute required closing bracket count
    depth = 0
    in_string = False
    escape_next = False
    end_pos = start_pos

    for i in range(start_pos, len(text)):
        char = text[i]

        if escape_next:
            escape_next = False
            continue

        if char == '\\':
            escape_next = True
            continue

        if char == '"' and not escape_next:
            in_string = not in_string
            continue

        if in_string:
            continue

        if char == '{':
            depth += 1
        elif char == '}':
            depth -= 1
            if depth == 0:
                end_pos = i + 1
                return text[start_pos:end_pos]

    return None


def _fix_json(json_str: str) -> Optional[str]:
    """
    Attempt to fix common JSON formatting issues.

    Args:
        json_str: Potentially malformed JSON string

    Returns:
        Fixed JSON string or None if unrecoverable
    """
    # Remove trailing commas
    fixed = re.sub(r',\s*([}\]])', r'\1', json_str)

    # Fix single quotes to double quotes (simple cases)
    try:
        json.loads(fixed)
        return fixed
    except json.JSONDecodeError:
        logger.debug("tool_call_parser: _fix_json verification failed, continuing fix attempts")

    # Remove comments (// and /* */)
    lines = []
    for line in fixed.split('\n'):
        # Remove // comments
        if '//' not in line:
            lines.append(line)
        else:
            idx = line.index('//')
            lines.append(line[:idx])

    fixed = '\n'.join(lines)

    # Remove /* */ block comments
    fixed = re.sub(r'/\*.*?\*/', '', fixed, flags=re.DOTALL)

    try:
        json.loads(fixed)
        return fixed
    except json.JSONDecodeError:
        return None


def extract_single_tool_call(text: str) -> Optional[Dict[str, Any]]:
    """
    Extract a single tool call from text.

    Use when you expect exactly one tool call (common in evaluation tasks).

    Args:
        text: Response text

    Returns:
        First tool call dict or None
    """
    calls = parse_tool_calls(text)
    return calls[0] if calls else None


def validate_tool_call(tool_call: Dict[str, Any]) -> Tuple[bool, Optional[str]]:
    """
    Validate a parsed tool call structure.

    Args:
        tool_call: Tool call dict

    Returns:
        Tuple of (is_valid, error_message)
    """
    if not isinstance(tool_call, dict):
        return False, "Tool call must be a dictionary"

    if 'tool' not in tool_call:
        return False, "Missing 'tool' field"

    if not isinstance(tool_call['tool'], str):
        return False, "'tool' must be a string"

    if 'params' in tool_call and not isinstance(tool_call['params'], dict):
        return False, "'params' must be a dictionary"

    return True, None


def format_tool_result(tool_name: str, result: Any, error: Optional[str] = None) -> str:
    """
    Format a tool execution result for AI consumption.

    Args:
        tool_name: Name of executed tool
        result: Tool result data
        error: Optional error message

    Returns:
        Formatted result string
    """
    if error:
        return json.dumps({
            'tool': tool_name,
            'success': False,
            'error': error,
        })

    return json.dumps({
        'tool': tool_name,
        'success': True,
        'result': result,
    })
