"""
Worker Template Generator (v2 0c DoD)
======================================

Auto-generates deployable worker startup scripts from config.json.

Features:
- Generate standalone worker.py script from config
- Generate systemd service file
- Generate start/stop/status check scripts
- Zero new dependencies (stdlib)

Author: Tical (Zize Tu)
Version: v0.3
"""

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


# =============================================================================
# Worker Template
# =============================================================================

WORKER_TEMPLATE = '''#!/usr/bin/env python3
"""
Auto-generated Worker Script
============================
Generated by generate_worker.py
Config: {config_path}
Generated at: {generated_at}

Usage:
    python3 worker.py [--config CONFIG] [--log-level LEVEL]

Environment Variables:
    TICAL_MODEL     Override model
    TICAL_API_KEY   Override API key env var
    TICAL_EDITION   Override edition (lite/full)
"""

import argparse
import asyncio
import logging
import os
import sys
from pathlib import Path

# Add EITElite to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from tical_code.core.worker_framework import WorkerFramework, WorkerConfig
from tical_code.core.session import SessionManager
from tical_code.core.usage import UsageTracker


def setup_logging(level: str = "INFO"):
    """Setup logging configuration."""
    logging.basicConfig(
        level=getattr(logging, level.upper()),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler("{log_file}", encoding="utf-8")
        ]
    )


def resolve_config(config_path: Optional[str] = None) -> WorkerConfig:
    """
    Resolve configuration from three sources:
    1. config.json (base)
    2. CLI args (override)
    3. Environment variables (highest priority)
    
    Environment Variables:
        TICAL_MODEL       Override model
        TICAL_API_KEY     Override API key env var name
        TICAL_EDITION     Override edition
        TICAL_WORK_DIR    Override working directory
        TICAL_LOG_LEVEL   Override log level
    """
    # Load from file or use defaults
    if config_path and os.path.exists(config_path):
        config = WorkerConfig.from_file(config_path)
    else:
        config = WorkerConfig()
    
    # Override with environment variables (highest priority)
    if os.environ.get("TICAL_MODEL"):
        config.model = os.environ["TICAL_MODEL"]
    if os.environ.get("TICAL_API_KEY"):
        config.api_key_env = os.environ["TICAL_API_KEY"]
    if os.environ.get("TICAL_EDITION"):
        config.edition = os.environ["TICAL_EDITION"]
    if os.environ.get("TICAL_WORK_DIR"):
        # Update enabled tools path if needed
        pass
    if os.environ.get("TICAL_LOG_LEVEL"):
        config.log_level = os.environ["TICAL_LOG_LEVEL"]
    
    # Expand paths
    config.expand_paths()
    
    return config


async def main():
    """Main worker entry point."""
    parser = argparse.ArgumentParser(description="EITElite Worker")
    parser.add_argument(
        "--config",
        type=str,
        default="{default_config}",
        help="Path to config.json"
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default="{default_log_level}",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging level"
    )
    parser.add_argument(
        "--once",
        action="store_true",
        help="Run one iteration and exit (for testing)"
    )
    args = parser.parse_args()
    
    # Resolve configuration
    config = resolve_config(args.config)
    config.log_level = args.log_level
    
    # Setup logging
    setup_logging(config.log_level)
    logger = logging.getLogger("worker")
    
    logger.info(f"Starting worker: {config.name}")
    logger.info(f"Edition: {config.edition}, Model: {config.model}")
    logger.info(f"Config: {args.config}")
    
    # Initialize usage tracker
    usage_tracker = UsageTracker()
    usage_tracker.start_session()
    
    # Create and run worker
    framework = WorkerFramework(config)
    
    try:
        await framework.bootstrap()
        
        if args.once:
            # Single iteration mode
            logger.info("Running single iteration (--once mode)")
            await framework.run_once()
        else:
            # Continuous loop mode
            logger.info("Entering run loop")
            await framework.run_loop()
            
    except KeyboardInterrupt:
        logger.info("Received interrupt signal")
    except Exception as e:
        logger.error(f"Worker error: {{e}}", exc_info=True)
    finally:
        logger.info("Shutting down worker")
        await framework.shutdown()
        usage_tracker.end_session()
        
        # Print usage summary
        summary = usage_tracker.get_summary()
        logger.info(f"Usage summary: {summary}")


if __name__ == "__main__":
    asyncio.run(main())
'''


SYSTEMD_SERVICE_TEMPLATE = '''[Unit]
Description=EITElite Worker - {worker_name}
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={work_dir}
ExecStart=/usr/bin/python3 {python_path} {worker_script} --config {config_path}
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
Environment="TICAL_API_KEY={api_key_env}"

# Resource limits
MemoryMax={memory_max}
CPUQuota={cpu_quota}

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths={work_dir}

[Install]
WantedBy=multi-user.target
'''


MANAGEMENT_SCRIPT_TEMPLATE = '''#!/bin/bash
# EITElite Worker Management Script
# Generated by generate_worker.py

set -e

WORKER_NAME="{worker_name}"
WORKER_SCRIPT="{worker_script}"
CONFIG_PATH="{config_path}"
PID_FILE="/run/EITElite/{worker_name}.pid"
LOG_FILE="{log_file}"

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log_info() {{
    echo -e "${{GREEN}}[INFO]${{NC}} $1"
}}

log_warn() {{
    echo -e "${{YELLOW}}[WARN]${{NC}} $1"
}}

log_error() {{
    echo -e "${{RED}}[ERROR]${{NC}} $1"
}}

check_root() {{
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root (for systemd service management)"
        exit 1
    fi
}}

start() {{
    log_info "Starting {worker_name}..."
    check_root
    systemctl start "tical-worker-{worker_name}.service"
    log_info "Worker started"
}}

stop() {{
    log_info "Stopping {worker_name}..."
    check_root
    systemctl stop "tical-worker-{worker_name}.service"
    log_info "Worker stopped"
}}

restart() {{
    log_info "Restarting {worker_name}..."
    stop
    sleep 2
    start
}}

status() {{
    systemctl status "tical-worker-{worker_name}.service" --no-pager
}}

logs() {{
    journalctl -u "tical-worker-{worker_name}.service" -f "$@"
}}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    logs)
        shift
        logs "$@"
        ;;
    *)
        echo "Usage: $0 {{start|stop|restart|status|logs}}"
        exit 1
        ;;
esac
'''


# =============================================================================
# Generator Class
# =============================================================================

class WorkerGenerator:
    """
    Generate worker deployment files from config.
    
    Example:
        gen = WorkerGenerator("/path/to/config.json")
        gen.generate(output_dir="/path/to/deploy")
    """
    
    def __init__(self, config_path: str):
        """
        Initialize generator.
        
        Args:
            config_path: Path to config.json
        """
        self.config_path = os.path.expanduser(config_path)
        self.config = self._load_config()
    
    def _load_config(self) -> Dict[str, Any]:
        """Load configuration from file."""
        if not os.path.exists(self.config_path):
            raise FileNotFoundError(f"Config not found: {self.config_path}")
        
        with open(self.config_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def _get_default(self, key: str, default: Any = None) -> Any:
        """Get config value with default."""
        return self.config.get(key, default)
    
    def generate(
        self,
        output_dir: str = ".",
        include_systemd: bool = True,
        include_management: bool = True
    ) -> List[str]:
        """
        Generate all worker deployment files.
        
        Args:
            output_dir: Output directory for generated files
            include_systemd: Generate systemd service file
            include_management: Generate management script
            
        Returns:
            List of generated file paths
        """
        output_dir = os.path.expanduser(output_dir)
        os.makedirs(output_dir, exist_ok=True)
        
        generated_files = []
        
        # 1. Generate worker.py
        worker_path = self._generate_worker_py(output_dir)
        generated_files.append(worker_path)
        
        # 2. Generate systemd service (if root)
        if include_systemd:
            service_path = self._generate_systemd_service(output_dir)
            generated_files.append(service_path)
        
        # 3. Generate management script
        if include_management:
            script_path = self._generate_management_script(output_dir)
            generated_files.append(script_path)
        
        return generated_files
    
    def _generate_worker_py(self, output_dir: str) -> str:
        """Generate worker.py script."""
        import datetime
        
        output_path = os.path.join(output_dir, "worker.py")
        
        content = WORKER_TEMPLATE.format(
            config_path=self.config_path,
            generated_at=datetime.datetime.now().isoformat(),
            default_config=self.config_path,
            default_log_level=self._get_default("log_level", "INFO"),
            log_file=self._get_default("log_file", "~/.EITElite/worker.log")
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Make executable
        os.chmod(output_path, 0o755)
        
        print(f"Generated: {output_path}")
        return output_path
    
    def _generate_systemd_service(self, output_dir: str) -> str:
        """Generate systemd service file."""
        service_dir = "/etc/systemd/system"
        service_name = f"tical-worker-{self.config.get('name', 'default')}.service"
        output_path = os.path.join(output_dir, service_name)
        
        content = SYSTEMD_SERVICE_TEMPLATE.format(
            worker_name=self.config.get('name', 'default'),
            user=self._get_default("systemd_user", "ubuntu"),
            work_dir=self._get_default("work_dir", os.path.dirname(os.path.dirname(output_dir))),
            python_path=sys.executable,
            worker_script=os.path.join(output_dir, "worker.py"),
            config_path=self.config_path,
            api_key_env=self._get_default("api_key_env", "GOOGLE_API_KEY"),
            memory_max=self._get_default("memory_max", "512M"),
            cpu_quota=self._get_default("cpu_quota", "100%")
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"Generated: {output_path}")
        print(f"To install: sudo cp {output_path} {service_dir}/ && sudo systemctl daemon-reload")
        return output_path
    
    def _generate_management_script(self, output_dir: str) -> str:
        """Generate management script."""
        output_path = os.path.join(output_dir, f"{self.config.get('name', 'worker')}_manage.sh")
        
        content = MANAGEMENT_SCRIPT_TEMPLATE.format(
            worker_name=self.config.get('name', 'default'),
            worker_script=os.path.join(output_dir, "worker.py"),
            config_path=self.config_path,
            log_file=self._get_default("log_file", "~/.EITElite/worker.log")
        )
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Make executable
        os.chmod(output_path, 0o755)
        
        print(f"Generated: {output_path}")
        return output_path


# =============================================================================
# CLI Entry Point
# =============================================================================

def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Generate worker deployment files from config"
    )
    parser.add_argument(
        "config",
        type=str,
        help="Path to config.json"
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=".",
        help="Output directory (default: current directory)"
    )
    parser.add_argument(
        "--no-systemd",
        action="store_true",
        help="Skip systemd service file generation"
    )
    parser.add_argument(
        "--no-management",
        action="store_true",
        help="Skip management script generation"
    )
    
    args = parser.parse_args()
    
    try:
        gen = WorkerGenerator(args.config)
        files = gen.generate(
            output_dir=args.output,
            include_systemd=not args.no_systemd,
            include_management=not args.no_management
        )
        
        print("\n" + "=" * 60)
        print("Generation complete!")
        print("=" * 60)
        print(f"Generated {len(files)} files:")
        for f in files:
            print(f"  - {f}")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
