# -*- coding: utf-8 -*-
"""EITElite Identity Proof Toolkit (IPT)"""

# ─── Build Watermark ──────────────────────────────────────────────
# This string identifies the build provenance. Public builds always
# carry this value. Commercial builds get a unique per-customer nonce
# generated by tools/watermark.py at release time.
__tical_watermark__ = "EITE_PUBLIC_OPEN_SOURCE"
# ──────────────────────────────────────────────────────────────────

from .decision_trace import DecisionTrace, DecisionTraceManager as TraceManager
from .observer import Observer
from .habits import HABIT_PATTERNS, match_habits

__all__ = [
    "DecisionTrace",
    "TraceManager",
    "Observer",
    "HABIT_PATTERNS",
    "match_habits",
]
